import { Router } from "express";
import { createFreelancer, deleteFreelancer, getFreelancerById, getFreelancers, updateFreelancer } from "../controllers/FreelancerController.js";
import { authMiddleWare } from "../middleware/authMiddleware.js";
const freelancerRouter=Router();
freelancerRouter.get("/",authMiddleWare,getFreelancers);
freelancerRouter.post("/create", authMiddleWare,createFreelancer);
freelancerRouter.get("/:id",authMiddleWare, getFreelancerById);
freelancerRouter.delete("/:id",authMiddleWare, deleteFreelancer);
freelancerRouter.put("/:id",authMiddleWare, updateFreelancer);
export default freelancerRouter;