import { Router } from "express";
import { deleteSavedJob, getSavedJobById, getSavedJobs, getSavedJobsByJobId, updateSavedJob } from "../controllers/SavedJobscontroller.ts";
import { authMiddleWare } from "../middleware/authMiddleware.ts";
const savedJobRouter=Router();
savedJobRouter.get("/",authMiddleWare,getSavedJobs);
savedJobRouter.get("/:id",authMiddleWare, getSavedJobById);
savedJobRouter.get("/:jobId",authMiddleWare, getSavedJobsByJobId);
savedJobRouter.delete("/:id", authMiddleWare,deleteSavedJob);
savedJobRouter.put("/:id",authMiddleWare, updateSavedJob);
export default savedJobRouter;