import { Router } from "express";
import { createUser, deleteUser, getUserById, getUsers, updateUser } from "../controllers/UserController.js";
import { authMiddleWare } from "../middleware/authMiddleware.js";
const userrouter = Router();
userrouter.get("/",authMiddleWare,getUsers);
userrouter.post("/create",authMiddleWare,createUser);
userrouter.get("/:id", authMiddleWare,getUserById);
userrouter.put("/:id",authMiddleWare, updateUser);
userrouter.delete("/:id", authMiddleWare,deleteUser);
export default userrouter;